baseURL = "https://taxonomias.netlify.com/"
languageCode = "es-cr"
title = "Taxonomías"

[taxonomies]
  tag = "tags"
  reino = "reinos"
  division = "divisiones"
  clase = "clases"
  orden = "ordenes"
  familia = "familias"
  genero = "generos"
