backend:
  name: github
  repo: guayom/taxonomias
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "especies" # Used in routes, e.g., /admin/collections/blog
    label: "Especies" # Used in the UI
    folder: "content/especies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre científico", name: "nombre_cientifico", widget: "string", required: false}
      - {label: "Reino", name: "reinos", widget: "list", required: false}
      - {label: "División", name: "divisiones", widget: "list", required: false}
      - {label: "Clase", name: "clases", widget: "list", required: false}
      - {label: "Órden", name: "ordenes", widget: "list", required: false}
      - {label: "Familia", name: "familias", widget: "list", required: false}
      - {label: "Género", name: "generos", widget: "list", required: false}
      - {label: "Especie", name: "especie", widget: "string", required: false}
      - {label: "Nombre común", name: "nombre_comun", widget: "string", required: false}
      - {label: "Nombre inglés", name: "nombre_ingles", widget: "string", required: false}
      - {label: "Otros nombres", name: "otros_nombres", widget: "list", required: false}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Links", name: "links", widget: "string", required: false}
      # - {label: "Notas", name: "notas", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - name: images
        label: Imágenes
        required: false
        widget: list
        fields:
          - {label: URL de la imagen, name: url, widget: string, required: false}
      - {label: "Estatus", name: "estatus", widget: "string", required: false}
      - {label: "Garrigues", name: "garrigues", widget: "string", required: false}
      - {label: "Vista", name: "vista", widget: "boolean", default: false}
      - {label: "La he visto en Los Cielos", name: "los_cielos", widget: "boolean", default: false}
      - {label: "Draft", name: "draft", widget: "hidden", default: "false", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
